### ISSUE TITLE
AAATA Developer API

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#205]
Thank you for your interest in TheRide’s API! We appreciate your patience during API testing, and are excited to share that we are now ready to begin the process of providing you access. If you’re still interested, please reply to Developers@TheRide.org (not to my email address) with the following information:

Email Address
First Name
Last Name
Company (if applicable)
Company Address (Optional)
Phone
Intended API use

---

A copy of the provided developer manual: 
[DeveloperAPIGuide.pdf](https://github.com/a2civictech/a2civictech/files/470750/DeveloperAPIGuide.pdf)

**Comment by vielmetti** [comment]
I have requested access to the API per the above instructions, and got an acknowledgement of my request right away from Don Kline.

**Comment by mckartha** [comment]
Interesting bits from the Clever Devices BusTime® Developer API Version1 Guide:

<hr>

_1.1_ **What is the BusTime®Developer API?**
The BusTime®Developer  API  allows you to  request  and  retrieve real-time data  directly  from BusTime®.  
Registered  third-party  developers  can make _HTTP  requests  for  data  and  receive_ **_XML responses**_ _from the BusTime®web server_. 

**2 Web Service**
...
A response is returned as a well-formed **XML document with a Content-Type of “text/xml”.** 
Get vehicles also supports a response as a **JSON document with a Content-Type of “application/json”**
...

The interpretation of the above statements and some examples from the API Guide suggests that the **getvehicles** API request, as well as many others _may_ return a JSON document rather than an XML document if the optional **_&format=json**_ parameter is included on the end of the HTTP GET request:
- http://localhost:8080/bustime/api/v1/getvehicles?key=89dj2he89d8j3j3ksjhdue93j&vid=6438,1295&tmres=s&format=json

<hr>

_1.2_ **What data is available through the API?**
Data available through the API includes:
- Vehicle locations
- Route data, comprising:
  - route lists
  - stop lists geo-positional route definitions
  - stop lists
  - etc.
- Prediction Data
- Service Bulletins

<hr>

**1.5 Is there a limit to the number of requests I can make to the Developer API?**
Yes. By default, _one API key can make a maximum of 10,000 requests per day_. 
If you believe that  you  will  require  more  than  10,000  daily  requests,  you  must  request  that  the  cap  on  your key be raised to handle the additional traffic.

**Comment by vielmetti** [comment]
Spoke at Public Comment at tonight's meeting (#204) and then spoke with AAATA staff afterwards. Mary Stasiak noted that the next task on their side is getting final legal approval for the terms and conditions of use for the data. The bus stop manager (name I didn't catch) said that his boss runs the Adopt-A-Stop program.

**Comment by vielmetti** [comment]
A prediction data endpoint looks like this through the AAATA proxy:

http://www.theride.org/DesktopModules/AATA.Endpoint/proxy.ashx?method=predictionsforstop&stpid=482

with output like

```
{
  "bustime-response": {
    "error": {
      "stpid": "482",
      "msg": "No service scheduled"
    }
  }
}
```

**Comment by vielmetti** [comment]
Sent a note of introduction between partners@transitapp.com and developers@theride.org in the hopes of Transit signing up for real time access through the API.

**Comment by vielmetti** [comment]
> Please disregard the email you received regarding the API key you requested. The system used to issue keys is being tested in preparation for the official launch. Your official key will come from this email address confirming the information you used to sign up.
> 
> We anticipate that the official keys will be issued today to any Developer that registered prior to 9/30/2016. All those that registered on or after 9/30/2016 will receive their key in following days.
> 
> As a reminder, all concerns, questions, and comments about the API should be directed to developers@theride.org.
> 
> Thank you,
> 
> Developer Support Team

**Comment by vielmetti** [comment]
Developer keys have been issued to those who applied.

**Comment by vielmetti** [comment]
AAATA has released v3 of the developer documentation, but the web interface only supports v2. New in v2 is JSON support.

Copy of the API v3 docs is at http://a2docs.org/view/440
