### ISSUE TITLE
AAATA API: JSON documents not returned when requested.

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#214]
"A well-formed XML or JSON document will be returned as a response to getpredictions."

curl 'http://rt.theride.org/bustime/api/v1/getpredictions?key=AAATAKEY&stpid=483&format=json'

returns an XML document instead of a JSON document. (Replace AAATAKEY with your key.)

**Comment by vielmetti** [comment]
Reported to the "developers@theride.org" address.

**Comment by vielmetti** [comment]
Acknowledged as a documentation bug. Get your XML parsers out if you want to deal with AAATA data.

**Comment by cdzombak** [comment]
ugh

**Comment by vielmetti** [comment]
So I suspect the right way to deal with AAATA data is to build a proxy makes a request with the API key, takes in XML ,and returns JSON, so that clients can avoid hauling in an XML parsing library.

**Comment by cdzombak** [comment]
> So I suspect the right way to deal with AAATA data is to build a proxy makes a request with the API key, takes in XML ,and returns JSON, so that clients can avoid hauling in an XML parsing library.

for building any real service based on this, that's the right approach for several reasons:
- as you note, JSON on most clients is easier to work with than XML
- you can keep your AAATA API key secret (on the server) instead of distributing it to clients; and if needed you can manage/filter access to your API
- you have a limit of calls/day per API key; your server is a clear place to implement caching to ensure you stay below that limit as you scale to many users
- you can own scaling your server setup instead of hoping AAATA scales with your userbase

… can you tell I've thought _a lot_ about this over the past couple of years?
